import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
    index("routes/home.tsx"),
    route("blog/:slug?", "routes/blog.tsx"),
    route("open-source/:slug?", "routes/open-source.tsx"),
    route("updates/:slug?", "routes/updates.tsx"),
    route("brand-kit", "routes/brand-kit.tsx"),
    route("about-us", "routes/about-us.tsx"),
    route("our-roadmap", "routes/our-roadmap.tsx"),
    route("terms-of-service/:slug?", "routes/terms-of-service.tsx"),
    route("comics/:shortUrl", "routes/comicseries.tsx"),
    route("comics/:shortUrl/:episodeId", "routes/comicissue.tsx"),
    route("creators/:shortUrl", "routes/creator.tsx"),
    route("lists/:id", "routes/list.tsx"),
    route("tagged/:tag", "routes/tag.tsx"),
    route("search/:term/:types?", "routes/search.tsx"),
    route("api/settings", "routes/api.settings.ts"),
    route("canny-login", "routes/canny-login.tsx"),
    route("download-app", "routes/download-app.tsx"),
    route("reset", "routes/reset.tsx"),
    route("logout", "routes/logout.tsx"),
    route("most-liked", "routes/most-liked.tsx"),
    route("most-discussed", "routes/most-discussed.tsx"),
    route("hosting-provider/:uuid", "routes/hosting-provider.tsx"),
    route("profile/setup", "routes/profile/setup.tsx"),
    route("profile/settings", "routes/profile/settings.tsx"),
    route("profile/notifications", "routes/profile/notifications.tsx"),
    route("profile/notification-settings", "routes/profile/notification-settings.tsx"),
    route("profile/edit", "routes/profile/edit.tsx"),
    route("profile/edit/username", "routes/profile/edit/username.tsx"),
    route("profile/edit/age", "routes/profile/edit/age.tsx"),
    route("profile/edit/email", "routes/profile/edit/email.tsx"),
    route("profile/edit/patreon", "routes/profile/edit/patreon.tsx"),
    route("profile/edit/bluesky", "routes/profile/edit/bluesky.tsx"),
    route("claim-creator/:uuid", "routes/claim-creator.tsx"),
    route("discord-art-challenge-2026", "routes/discord-art-challenge-2026.tsx"),
    route(":username", "routes/profile.tsx"),
] satisfies RouteConfig;
