FROM node:20.17

# Create and use /app
WORKDIR /app

# Update and install system dependencies
RUN apt-get update -y && apt-get upgrade -y && \
    apt-get install -y apt-utils apt-transport-https ca-certificates

# Install Yarn
RUN curl -o- -L https://yarnpkg.com/install.sh | bash

# Add Yarn to PATH
ENV PATH="/root/.yarn/bin:$PATH"

# Copy package manifests
COPY package.json yarn.lock ./
COPY packages/public/package.json ./packages/public/package.json
COPY packages/shared-server/package.json ./packages/shared-server/package.json
COPY graphql-server/package.json ./graphql-server/package.json

# Install root dependencies
RUN yarn install

# Copy the rest of the source code
COPY packages/public/ ./packages/public/
COPY packages/shared-server/ ./packages/shared-server/
COPY graphql-server/ ./graphql-server/

# Build packages
WORKDIR /app/graphql-server
RUN yarn build

# Set environment
ENV NODE_ENV=production

EXPOSE 3010

# Run the server
CMD ["node", "dist/server.js"]
