/* AUTO-GENERATED by generate-font-subsets.ts — do not edit. Regenerate with: yarn generate-font-subsets */
import font0 from './generated/source-sans-3-latin-400.woff2?url';
import font1 from './generated/source-sans-3-latin-600.woff2?url';
import font2 from './generated/source-sans-3-latin-800.woff2?url';

export const fontPreloads: string[] = [font0, font1, font2];
