import fs from 'fs';
import path from 'path';
import subsetFont from 'subset-font';

// Splits the Source Sans 3 variable font into per-script woff2 subsets and
// co-generates the matching @font-face CSS and preload manifest, so the
// unicode-range declarations can never drift from the file contents.
// Run from website/: yarn generate-font-subsets

const SOURCE_FONT = './fonts-src/SourceSans3-VF.ttf';
const OUT_DIR = './app/fonts/generated';
const CSS_OUT = './app/fonts/fonts.css';
const PRELOADS_OUT = './app/fonts/preloads.ts';

const FONT_FAMILY = 'Source Sans 3';
// Intentional weight policy (July 2026): the site uses exactly these weights.
// font-medium was removed site-wide as a no-op (500 fell back to 400), and
// font-bold (700) deliberately resolves up to 800 — that's the approved look.
// Audit Tailwind font-* class usage before changing this list.
const WEIGHTS = [400, 600, 800];
const PRELOAD_SUBSET = 'latin';

// Google Fonts' canonical subset ranges for Source Sans 3, in Google's CSS
// order: latin must come LAST, because the last matching @font-face wins for
// codepoints that appear in multiple ranges (e.g. U+0301, U+0304, U+0308).
const SUBSETS: Record<string, string> = {
  'cyrillic-ext': 'U+0460-052F, U+1C80-1C8A, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F',
  'cyrillic': 'U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116',
  'greek-ext': 'U+1F00-1FFF',
  'greek': 'U+0370-0377, U+037A-037F, U+0384-038A, U+038C, U+038E-03A1, U+03A3-03FF',
  'vietnamese': 'U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+0300-0301, U+0303-0304, U+0308-0309, U+0323, U+0329, U+1EA0-1EF9, U+20AB',
  'latin-ext': 'U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF',
  'latin': 'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD',
};

function rangeToText(range: string): string {
  return range.split(',').flatMap(part => {
    const [start, end = start] = part.trim().replace(/^U\+/i, '').split('-').map(hex => parseInt(hex, 16));
    return Array.from({ length: end - start + 1 }, (_, i) => start + i);
  }).map(cp => String.fromCodePoint(cp)).join('');
}

const GENERATED_BANNER = `AUTO-GENERATED by generate-font-subsets.ts — do not edit. Regenerate with: yarn generate-font-subsets`;

const source = fs.readFileSync(SOURCE_FONT);
fs.rmSync(OUT_DIR, { recursive: true, force: true });
fs.mkdirSync(OUT_DIR, { recursive: true });

let css = `/* ${GENERATED_BANNER} */\n`;
const preloadFiles: string[] = [];

for (const [subsetName, range] of Object.entries(SUBSETS)) {
  const text = rangeToText(range);
  for (const weight of WEIGHTS) {
    const woff2 = await subsetFont(source, text, {
      targetFormat: 'woff2',
      variationAxes: { wght: weight },
    });
    const fileName = `source-sans-3-${subsetName}-${weight}.woff2`;
    fs.writeFileSync(path.join(OUT_DIR, fileName), woff2);
    if (subsetName === PRELOAD_SUBSET) preloadFiles.push(fileName);
    console.log(`${fileName} (${(woff2.length / 1024).toFixed(1)} KB)`);

    css += `
/* ${subsetName} ${weight} */
@font-face {
  font-family: '${FONT_FAMILY}';
  font-style: normal;
  font-weight: ${weight};
  font-display: swap;
  src: url('./generated/${fileName}') format('woff2');
  unicode-range: ${range};
}
`;
  }
}

fs.writeFileSync(CSS_OUT, css);

fs.writeFileSync(
  PRELOADS_OUT,
  `/* ${GENERATED_BANNER} */\n` +
  preloadFiles.map((fileName, i) => `import font${i} from './generated/${fileName}?url';`).join('\n') +
  `\n\nexport const fontPreloads: string[] = [${preloadFiles.map((_, i) => `font${i}`).join(', ')}];\n`
);

console.log(`\nWrote ${Object.keys(SUBSETS).length * WEIGHTS.length} subsets, ${CSS_OUT}, and ${PRELOADS_OUT}`);
